---
- name: Change NTP Servers and Upload Results
  hosts: checkpoint_firewalls
  gather_facts: no  # No need for Python-based fact gathering
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_network_os: checkpoint
    ansible_user: "admin"
    ansible_password: "your_password"

  tasks:
    - name: Get NTP servers
      check_point_mgmt:
        command: show-ntp
        session_data: yes
      register: ntp_output

    - name: Save NTP server output to CSV file
      copy:
        content: |
          Hostname,NTP Servers
          {{ inventory_hostname }},{{ ntp_output.json.result.servers | join(',') }}
        dest: "/tmp/ntp_output.csv"

    - name: Upload CSV file to SharePoint
      uri:
        url: "https://fma.sharepoint.com/sites/BNZ/Shared%20Documents/Checkpoint"
        method: POST
        headers:
          Content-Type: "multipart/form-data"
        src: "/tmp/ntp_output.csv"
        status_code: 201
