---
- name: Change Password Policy on Gaia
  hosts: all
  gather_facts: no
  vars:
    password_policy:
      enforce-uppercase: true
      enforce-lowercase: true
      enforce-numbers: true
      enforce-special-characters: true
      min-password-length: 12
      max-password-age: 90
      remember-passwords: 5

  tasks:
    - name: Authenticate to Gaia API
      uri:
        url: "https://{{ ansible_host }}/web_api/login"
        method: POST
        headers:
          Content-Type: application/json
        body:
          username: "{{ gaia_username }}"
          password: "{{ gaia_password }}"
        body_format: json
        return_content: yes
      register: auth_response
      failed_when: "'sid' not in auth_response.json"
      tags:
        - auth

    - name: Set password policy
      uri:
        url: "https://{{ ansible_host }}/web_api/set-password-policy"
        method: POST
        headers:
          Content-Type: application/json
          X-chkp-sid: "{{ auth_response.json['sid'] }}"
        body:
          password-policy: "{{ password_policy }}"
        body_format: json
        return_content: yes
      register: password_policy_response
      failed_when: "'success' not in password_policy_response.json or not password_policy_response.json['success']"
      tags:
        - password-policy

    - name: Logout from Gaia API
      uri:
        url: "https://{{ ansible_host }}/web_api/logout"
        method: POST
        headers:
          Content-Type: application/json
          X-chkp-sid: "{{ auth_response.json['sid'] }}"
        body: {}
        body_format: json
        return_content: yes
      tags:
        - logout
